.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge3 - Debug ]----------"
	@cd "Challenge3" && "$(MAKE)" -f  "Challenge3.mk"
clean:
	@echo "----------Cleaning project:[ Challenge3 - Debug ]----------"
	@cd "Challenge3" && "$(MAKE)" -f  "Challenge3.mk" clean
