.PHONY: clean All

All:
	@echo "----------Building project:[ challenge_test - Debug ]----------"
	@cd "challenge_test" && "$(MAKE)" -f  "challenge_test.mk"
clean:
	@echo "----------Cleaning project:[ challenge_test - Debug ]----------"
	@cd "challenge_test" && "$(MAKE)" -f  "challenge_test.mk" clean
