.PHONY: clean All

All:
	@echo "----------Building project:[ ex1 - Debug ]----------"
	@cd "ex1" && "$(MAKE)" -f  "ex1.mk"
clean:
	@echo "----------Cleaning project:[ ex1 - Debug ]----------"
	@cd "ex1" && "$(MAKE)" -f  "ex1.mk" clean
