.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge2 - Debug ]----------"
	@cd "Challenge2" && "$(MAKE)" -f  "Challenge2.mk"
clean:
	@echo "----------Cleaning project:[ Challenge2 - Debug ]----------"
	@cd "Challenge2" && "$(MAKE)" -f  "Challenge2.mk" clean
