.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_with_non_member_operators - Debug ]----------"
	@cd "Challenge" && "$(MAKE)" -f  "Challenge_with_non_member_operators.mk"
clean:
	@echo "----------Cleaning project:[ Challenge_with_non_member_operators - Debug ]----------"
	@cd "Challenge" && "$(MAKE)" -f  "Challenge_with_non_member_operators.mk" clean
